export const USER_LOGIN = 'USER_LOGIN';
export const USER_FOUND = 'USER_FOUND';
export const FETCH_POST_LIKES = 'FETCH_POST_LIKES';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_FAIL_FB = 'LOGIN_FAIL_FB';
export const LOGIN_FAIL_CONFIRM = 'LOGIN_FAIL_CONFIRM';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_SUCCESS';

export const POST_CREATE_UPDATE = 'POST_CREATE_UPDATE';
export const POST_CREATE_SAVE = 'POST_CREATE_SAVE';
export const POST_EDIT_UPDATE = 'POST_EDIT_UPDATE';
export const POST_SAVE_SUCCESS = 'POST_SAVE_SUCCESS';
export const POST_APPEND = 'POST_APPEND';
export const POST_DELETE = 'POST_DELETE';
export const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';
export const POST_SET_ACTIVE = 'POST_SET_ACTIVE';
export const POST_RESET_ACTIVE = 'POST_SET_ACTIVE';
export const POST_SHOW_DELETE_MODAL = 'POST_SHOW_DELETE_MODAL';
export const POST_HIDE_DELETE_MODAL = 'POST_HIDE_DELETE_MODAL';
export const POST_UNAVAILABLE = 'POST_UNAVAILABLE';
export const POST_UNAVAILABLE_CONFIRM = 'POST_UNAVAILABLE_CONFIRM';
export const POST_FETCH_LIKED_BY = 'POST_FETCH_LIKED_BY';
export const POST_CLEAR_LIKED_BY = 'POST_CLEAR_LIKED_BY';

export const COMMENT_CREATE_UPDATE = 'COMMENT_CREATE_UPDATE';
export const COMMENT_CREATE_SAVE = 'COMMENT_CREATE_SAVE';
export const COMMENT_EDIT_UPDATE = 'COMMENT_EDIT_UPDATE';
export const COMMENT_SAVE_SUCCESS = 'COMMENT_SAVE_SUCCESS';
export const COMMENT_DELETE = 'COMMENT_DELETE';
export const COMMENTS_FETCH_SUCCESS = 'COMMENTS_FETCH_SUCCESS';
export const COMMENTS_POPULATE = 'COMMENTS_POPULATE';
export const COMMENTS_CLEAR = 'COMMENTS_CLEAR';
export const FETCH_POST_COMMENT_LIKES = 'FETCH_POST_COMMENT_LIKES';
export const COMMENT_LIKES_CLEAR = 'COMMENT_LIKES_CLEAR';
export const FETCH_COMMENT_LIKED_BY = 'FETCH_COMMENT_LIKED_BY';
export const COMMENT_LIKED_BY_CLEAR = 'COMMENT_LIKED_BY_CLEAR';

export const FETCH_PIJN_LOG = 'FETCH_PIJN_LOG';

export const FETCH_PINBOARD = 'FETCH_PINBOARD';

export const FETCH_FAVORITES = 'FETCH_FAVORITES';

export const SAVE_NAVIGATION = 'SAVE_NAVIGATION';

export const SEARCH_UPDATE = 'SEARCH_UPDATE';

export const FRIEND_STATUS = 'FRIEND_STATUS';
export const FRIEND_POSTS_FETCH_SUCCESS = 'FRIEND_POSTS_FETCH_SUCCESS';
export const FRIEND_CLEAR = 'FRIEND_CLEAR';

export const FETCH_REQUESTS = 'FETCH_REQUESTS';

export const FETCH_FRIEND_LIST = 'FETCH_FRIEND_LIST';

export const FETCH_USER_FEED = 'FETCH_USER_FEED';
export const UPDATE_USER_FEED = 'UPDATE_USER_FEED';

export const FETCH_POST_NOTES = 'FETCH_POST_NOTES';
export const NOTES_CLEAR = 'NOTES_CLEAR';

export const FETCH_CHAT = 'FETCH_CHAT';
export const CHAT_CLEAR = 'CHAT_CLEAR';

export const FETCH_CHAT_LIST = 'FETCH_CHAT_LIST';
export const CHAT_LIST_CLEAR = 'CHAT_LIST_CLEAR';
export const MESSAGES_COUNT = 'MESSAGES_COUNT';

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const NOTIFICATIONS_COUNT = 'NOTIFICATIONS_COUNT';

export const SHOW_VISIBLE_TO_MODAL = 'SHOW_VISIBLE_TO_MODAL';
export const HIDE_VISIBLE_TO_MODAL = 'HIDE_VISIBLE_TO_MODAL';
