export const USER_LOGIN = 'USER_LOGIN';
export const USER_FOUND = 'USER_FOUND';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_SUCCESS';

export const POST_CREATE_UPDATE = 'POST_CREATE_UPDATE';
export const POST_CREATE_SAVE = 'POST_CREATE_SAVE';
export const POST_EDIT_UPDATE = 'POST_EDIT_UPDATE';
export const POST_SAVE_SUCCESS = 'POST_SAVE_SUCCESS';
export const POST_DELETE = 'POST_DELETE';
export const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';

export const COMMENT_CREATE_UPDATE = 'COMMENT_CREATE_UPDATE';
export const COMMENT_CREATE_SAVE = 'COMMENT_CREATE_SAVE';
export const COMMENT_EDIT_UPDATE = 'COMMENT_EDIT_UPDATE';
export const COMMENT_SAVE_SUCCESS = 'COMMENT_SAVE_SUCCESS';
export const COMMENT_DELETE = 'COMMENT_DELETE';
export const COMMENTS_FETCH_SUCCESS = 'COMMENTS_FETCH_SUCCESS';
export const COMMENTS_POPULATE = 'COMMENTS_POPULATE';

export const FETCH_PIJN_LOG = 'FETCH_PIJN_LOG';
export const SAVE_NAVIGATION = 'SAVE_NAVIGATION';

export const LIKE_JOB = 'LIKE_JOB';
export const CLEAR_LIKED_JOBS = 'CLEAR_LIKED_JOBS';
